UKHomeOffice/paf

.drone.yml
=> merge feature/paf-16 to main.

.eslintrc.json, assets/js/index.js, server.js
- Set up linting
- To enable linting testing on pipeline
=> PAF-26: setup linting

apps/paf/index.js, package.json, server.js, test/_ui-integration/paf/application.spec.js, test/helpers/supertest_session/session-data/base.js, test/helpers/supertest_session/session-data/paf/steps.js, test/helpers/supertest_session/supertest-utilities.js, test/helpers/utilities.js, test/setup.js, yarn.lock
- Create initial UI integration tests
- To allow for testing in pipeline
=> PAF-27: create UI integration tests

apps/common/index.js, apps/common/translations/src/en/pages.json, apps/common/views/content/start.md, apps/paf/behaviours/aggregator.js, apps/paf/behaviours/limit-person.js, apps/paf/behaviours/person-number.js, apps/paf/data/airlineCompanies.json, apps/paf/data/countriesList.json, apps/paf/data/nationalities.json, apps/paf/data/occupation.json, apps/paf/data/trainCompanies.json, apps/paf/fields/index.js, apps/paf/index.js, apps/paf/sections/summary-data-sections.js, apps/paf/translations/src/en/buttons.json, apps/paf/translations/src/en/fields.json, apps/paf/translations/src/en/pages.json, apps/paf/views/add-another.html, apps/paf/views/content/declaration.md, apps/paf/views/partials/car-group.html, apps/paf/views/partials/hgv-group.html, apps/paf/views/partials/lorry-group.html, apps/paf/views/partials/van-group.html, apps/paf/views/report-person-transport-type.html, apps/paf/views/report-person-transport.html, assets/js/index.js, assets/scss/app.scss
- Add 'the person' section part of form
- Add person loop functionality
- Limit number of additional people that can be added
- Create relevant tests
=> PAF-13: add person loop - WIP

bin/deploy.sh, kube/configmaps/file-vault-branch-configmap.yml, kube/file-vault/file-vault-deployment.yml, kube/file-vault/file-vault-ingress.yml, kube/file-vault/file-vault-network-policy.yml, kube/file-vault/file-vault-service.yml
=> added filevault setup

apps/paf/data/companyTypes.json, apps/paf/translations/src/en/fields.json, apps/paf/translations/src/en/pages.json, apps/paf/views/content/declaration.md, apps/paf/views/partials/confirmation-alert.html
Content changes such as:
- amend header statements to questions
- amend declaration page
- amend confirmation panel
- To improve consistency and adherence to accessibility requirements
- tests passing locally
=> Content changes

kube/file-vault/file-vault-ingress.yml
=> Revert "fv-ingress annotations change"

bin/deploy.sh, kube/ims-resolver/ims-resolver-deploy.yml
Deploy ims resolver as part of PRs
Because we need the ims-resolver to send the form data and docs to the IMS system
=> PAF-50 Deploy ims-resolver

bin/deploy.sh, kube/app/ingress-external.yml
=> added external ingress for poise access

kube/ims-resolver/ims-resolver-deploy.yml
New image deployment for ims-resolver 
to connect to the private link from ACP to EBSA
=> PAF-135 Deploy ims-resolver for the private link

.drone.yml
=> removed steps on push

.snyk, yarn.lock
- whitelist request vuln in snyk
- update xml2js
- whitelist indirect xml2js vuln in  snyk
- Causing snyk step to fail in drone
- Added request vuln to ignore list in snyk
- Updated xml2js
- Added indirect xml2js vuln to ignore list in snyk
=> fix snyk issues

.drone.yml, bin/deploy.sh, kube/file-vault/file-vault-deployment.yml
User unable to upload documents on Public Allegations Form
Configuration related to file-vault and certificate are missing
I have added config details in deploy.sh and file-vault-deployment.yaml
=> PAF-100 Fix for user unable to upload documents on Public Allegations Form

config.js
Changed sqs config to send to aws sqs
The sqs config for sending to sqs on LocalStack is different to sending to sqs on AWS
Updated config for sqs credentials
=> Changed sqs config to send to AWS SQS

kube/app/deployment.yml, kube/ims-resolver/ims-resolver-deploy.yml
ims-resolver processing new data structure that includes additional people and attachments
=> Latest ims-resolver

apps/paf/models/file-upload.js
=> fixed file upload error

.drone.yml
=> trigger build

.drone.yml
=> cronjobfix

test/_unit/server.spec.js
unit test failed 
failed to pass behavioursTimeFormatterStub as parameter to behaviour 
added the behavioursTimeFormatterStub
test locally
=> fix unit test fail in server.spec.js

package.json, yarn.lock
[HOFF-638 ](https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-638).- changing Queen's crown to King's crown logo
 
The Gov.uk crown logo changed
 
yarn install hof@20.4.0
 
Tested locally
 
 
=> HOFF-638 Update PAF to HOF v20.4.0

apps/paf/fields/index.js, kube/app/deployment.yml, kube/file-vault/file-vault-deployment.yml, kube/ims-resolver/ims-resolver-deploy.yml
Updated the prod secret names for sqs and s3 in the deployment files
The secret names in the deployment files were for branch and UAT only
Created if else conditions for prod/not-prod and added the secret for prod
Deploy and test branch and UAT to make sure nothing is broken by submitting and verifying and then deploy to prod
=> Update prod secrets

.drone.yml, bin/deploy.sh, kube/app/ingress-external.yml, kube/app/networkpolicy-external.yml, kube/file-vault/file-vault-ingress.yml
Added certmounts t to prod deployment
=> Prod deployment test

bin/deploy.sh, kube/certmounts/certmounts-prod.yml
* Mount Cert to pod as configmap
* This error seen in logs "unable to verify the first certificate"
* Above error seen in ims-resolver container logs
* Deploy cert via  Drone CI pipeline
=> PAF-253: resolve IMS-resolver issue

bin/deploy.sh
* Certs are being overwritten 
* remove kube/certmounts
=> PAF-253: Fix Cert Overwrite issue

bin/deploy.sh, kube/ims-resolver/ims-resolver-deploy.yml
=> PAF-253: testing with certchain for prod

kube/ims-resolver/ims-resolver-deploy.yml
**What?**
Try to retrieve an existing case and also isolate the create case api which seems to cause the 500 error
**Why?**
create case api which seems to cause the 500 error on prod
=> Fix prod 500 error

bin/deploy.sh, kube/ims-resolver/ims-resolver-deploy.yml
Disable TLS to hit the IMS system endpoint
Currently the certs are not working so try hitting the end point without TLS
=> PAF-264 Test integration without TLS

bin/deploy.sh
=> Prod 500 error 

bin/deploy.sh, kube/ims-resolver/ims-resolver-deploy.yml
add the mouting of the cert in the deploy.sh & turn TLS back on
We think the order of the certs was wrong so we are hoping that will fix the issue that's why we are adding it back
=> PAF-264 Readd the certmount & turn TLS back on

bin/deploy.sh, kube/ims-resolver/ims-resolver-deploy.yml
**What?**
* Remove secure connection and certs temporarily
**Why?**
* Currently we can curl but we can't send data to IMS via the app, strip out this complexity to see if it helps
=> Test for Prod 500 error - Remove certs temporarily 

kube/ims-resolver/ims-resolver-deploy.yml
Update the ims-resolver image to one with extra logging added for client and createCase methods
Investigate these objects to see if it helps diagnose issue in PRD1
=> Update ims-resolver image to one with advanced logging

apps/paf/models/file-upload.js, kube/ims-resolver/ims-resolver-deploy.yml, lib/utils.js
**What?**
Remove extra logging to release to prod
**Why?**
Logging extra information could be a security risk
=> Remove extra logging in ims-resolver and paf for prod release

kube/ims-resolver/ims-resolver-deploy.yml
Update ims-resolver image
The update includes adding a reject parameter to the handleMessage function
The lack of the reject parameter meant that it was undefined when the function tries to call it. This update should fix that issue
To test this in branch before merge to UAT.
=> Update ims-resolver image to fix failed reject from resolver in the case of bad message

kube/ims-resolver/ims-resolver-deploy.yml
IMS resolver pod restarting issue has been addressed recently. Upon further investigation We noticed the restarts are due to OOM ( Out of Memory) error can be seen while we describe the pod. Container is not allowed to use more than its memory limit. If a Container allocates more memory than its limit, the Container becomes a candidate for termination. If the Container continues to consume memory beyond its limit, the Container is terminated.
refer to ticket : https://collaboration.homeoffice.gov.uk/jira/browse/PAF-289
As this is not an application error, it wont appear in Opensearch Logs. Sysdig Monitoring dashboards have helped us to confirm again with the amount of memory utlized which resulted in pod restarts. Memory utlized by the pod is 656 MB (625.61 MiB) on the latest restart date …
=> PAF-289: Increase Memory of IMS-Resolver container

.snyk, apps/paf/translations/src/en/validation.json
[ACRS-259](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-259) - Generic errors - No further details about the error message
Some field are missing validation error message
- added validation type error and error messages in validation.js file for fields
Tested locally
=> PAF-259 Bugfix No Error message

kube/ims-resolver/ims-resolver-deploy.yml, yarn.lock
-  Amend field format - [PAF-301](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-301)
- 'Date received' field in IMS showing incorrect date on submission 
- time field had a typo and showed the time incorrectly when minutes was in single digits
- update ims-resolver image to amend date and time format in ims
- update yarn.lock to fix vulns
- tests passing locally, tested on branch
=> PAF-301: Amend date and time format
