apps/paf/fields/index.js
apps/paf/sections/summary-data-sections.js
apps/paf/translations/src/en/pages.json
config.js
test/_ui-integration/paf/application.spec.js
test/_unit/behaviours/aggregator.spec.js
test/_unit/behaviours/limit-person.spec.js
test/_unit/behaviours/transport-behaviour.spec.js
test/_unit/sections/summary-data-sections.spec.js

- Add unit and ui tests for person section
- Format date of birth fields
- Remove incomplete other-info section from summary data sections as they were causing tests to fail( they can be added back in once the section has been completed and added to check answers page)
- Amend check answers section headers for consistency
- Format field/index.js after rebase
- Test person section
- Improve consistency with field and header names
- Clean up after multiple branch merges
tests passing locally

Paf tests and merge clean up

---

apps/paf/fields/index.js
apps/paf/index.js
apps/paf/sections/summary-data-sections.js
apps/paf/translations/src/en/fields.json
apps/paf/translations/src/en/pages.json
test/_unit/sections/summary-data-sections.spec.js

- Add pages for other info section
- Add relevant tests
- Part of PAF form
- Test passing  locally

PAF-45: add 'other info' section pages

---

apps/paf/behaviours/set-navigation-section.js
apps/paf/index.js
apps/paf/views/layout.html
apps/paf/views/partials/main-content-left.html
apps/paf/views/partials/side-nav.html
assets/scss/app.scss
hof.settings.json
server.js
test/_unit/behaviours/set-navigation-section.spec.js
test/_unit/server.spec.js

- Create get-section behaviour to configure navigation menu links
- Remove next property from index.js for pages preceeding section pages as they were preventing this pages from being reached (the next property for these pages have now been configured in the get-section behaviour)
- Add views for layout, side-nav and main content
- Add css for side navigation
- Amend css for links so disabled links do not have govuk-link class
- Add get-section behaviour to hof.settings so it is applied across all pages 
- Add behaviours in hof.settings to server.js
- Add relevant tests
- Part of PAF form
- tests passing locally

PAF-39: add navigation design

---

apps/paf/behaviours/disable-file-upload.js
apps/paf/behaviours/limit-documents.js
apps/paf/behaviours/remove-file.js
apps/paf/behaviours/save-file.js
apps/paf/fields/index.js
apps/paf/index.js
apps/paf/models/file-upload.js
apps/paf/sections/summary-data-sections.js
apps/paf/translations/src/en/fields.json
apps/paf/translations/src/en/pages.json
apps/paf/translations/src/en/validation.json
apps/paf/views/list-add-looped-files.html
apps/paf/views/other-info-file-upload.html
apps/paf/views/partials/looped-files.html
apps/paf/views/partials/side-nav.html
assets/scss/app.scss
config.js
mock-apis.js
mocks/image-upload.js
server.js
test/_ui-integration/paf/application.spec.js
test/_unit/behaviours/limit-documents.spec.js
test/_unit/behaviours/remove-file.spec.js
test/_unit/behaviours/save-file.spec.js
test/_unit/models/file-upload.spec.js
test/_unit/sections/summary-data-sections.spec.js
test/_unit/server.spec.js

- Add upload model for uploading attachments functionality
- Add  save, delete and disable file behaviours for uploading attachments functionality
- Add validation for number of attachments added
- Add relevant views
- Add ui and unit tests
- Amend content in side nav view

PAF-11: Attachments

---

apps/paf/behaviours/vehicle-toggle-formatter.js
apps/paf/index.js
apps/paf/views/partials/crime-van-group.html
apps/paf/views/partials/report-person-transport-van-group.html
lib/ims-hof-fields-map.json
lib/ims-hof-values-map.json
test/_unit/behaviours/vehicle-toggle-formatter.spec.js

- Format radio toggles for vehicle-type, boat-type, and report transport-type so they are mapped to IMS values
- Applied the formatting behaviours to the declaration page, to avoid conflicts with other behaviours
- Add missing values and field objects for mapping
- The radio toggle values had a different field name and so were not being mapped 
- Created a behaviour to set toggled field values to the relevant vehicle-type, boat-type or report-person-transport-type so they are mapped to IMS correctly
Tests passing

Format vehicle-type, boat-type, report-person-transport radio toggle values for mapping

---

apps/paf/fields/index.js

- remove url validate copied into person and company manager fields
- was causing validation error to flag when url validation was not required
- removed url validate from person and company manager fields
tests passing locally

remove url validate from person and company manager fields

---

apps/paf/models/file-upload.js

What?
[PAF-180](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-180)
Why?
Unable to upload filename with uppercase
How?
URL parse added in file-upload.js
Testing?
Testing pass locally

PAF-180 Filename with uppercase bug fix

---

apps/paf/fields/index.js

Option not showing correct format on 'When will crime happen?' Page   - [PAF-178](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-178)
In When will crime happen?' page  the third option is not showing correct format
In index.js in fields  the third option in when-will-crime-happen was changed to when-will-crime-happen-unknown from unknown
Testing pass locally

PAF-178 Fix option not showing correct format on 'When will crime happen?'  page

---

apps/paf/fields/index.js
apps/paf/translations/src/en/validation.json

Missing Validation  - What is your date of birth? Page - [PAF-177](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-177)
When the validation was triggered the message was missing
- Added validation for  'before', after1900Validator in about-you-dob  fields  in fields/index.js
- Validation messages added for  date,  before and after in validation.json
Testing passing  locally

PAF-177 Validation for date of birth bug fix

---

apps/paf/behaviours/set-transport-toggle.js
apps/paf/index.js
apps/paf/views/partials/crime-car-group.html
apps/paf/views/partials/crime-carrier-group.html
apps/paf/views/partials/crime-general-cargo-group.html
apps/paf/views/partials/crime-hgv-group.html
apps/paf/views/partials/crime-lorry-group.html
apps/paf/views/partials/crime-van-group.html
apps/paf/views/partials/crime-vessel-group.html
apps/paf/views/partials/report-person-transport-car-group.html
apps/paf/views/partials/report-person-transport-hgv-group.html
apps/paf/views/partials/report-person-transport-lorry-group.html
apps/paf/views/partials/report-person-transport-van-group.html
test/_unit/behaviours/set-transport-toggle.spec.js

- Radio toggle bug fix
- To fix bug which caused vehicle and boat types selected from radio toggle to unset once the user left the page
- Added a behaviour that set the relevant radio toggle transport field as 'checked' when the user selects it.
- Tests passing locally

Paf 66 radio toggle bug fix

---

apps/paf/fields/index.js
apps/paf/translations/src/en/validation.json

Missing Validation for future date - Future date is accepted on the person date of birth Page - [PAF-134](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-134)
When the validation was triggered the message was missing for future date
- Validation added for report person dob and person person add dob   for future date filelds in index.js
- Validation messages added for report person dob and person add dob for future date in validation.json
Testing passing  locally

PAF-134  Future date is accepted on the person date of birth bug fix

---

apps/paf/fields/index.js

PAF-134-validator patch
Existing code shows lint error  due to after1900Validator which appeared twice in fields index.js
Removed after1900Validator in fields index.js which appeared twice
Tested locally

PAF-134-validator-patch

---

apps/paf/behaviours/time-formatter.js
apps/paf/fields/index.js
apps/paf/index.js
apps/paf/translations/src/en/fields.json
apps/paf/translations/src/en/pages.json
apps/paf/translations/src/en/validation.json
apps/paf/views/date-time-crime-will-happen.html
assets/scss/app.scss
hof.settings.json
test/_unit/behaviours/time-formatter.spec.js
test/_unit/server.spec.js

- Add a custom time field view for PAF. - [PAF-44](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-44)
Part of PAF app
- add time fields for 'hour' and 'minute'
- add custom time fields in view
- add change link to time field on check answers page
- add styling to time fields
- add behaviour to format time
- add tests for time formatter behaviour
Tests running locally

PAF-44: PAF time field

---

lib/add-allegation-data.js
test/_unit/behaviours/add-allegation-data.spec.js

Altered behaviour as part of form submission to allow file-vault URLs for attachments to be added from the session into the SQS payload and sent to queue.
Removed an unnecessary log of image array. This comes up in other logs elsewhere in the behaviour.
Existing code was blocking this. Will be a prerequisite to sending the attachment files to IMS from the ims-resolver.
Removed existing conditionals that stopped the array of file-vault URLs for attachements/uploaded files from being brought from the session into the SQS payload.
Altered the tree structure so it will be simpler to extract the file URL array from the payload for processing in the ims-resolver.
Tested locally using the UAT queue.

PAF-74 Allow attachment URLs into SQS payload

---

apps/paf/translations/src/en/pages.json

[PAF-197](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-197) Paf-when-will-crime-happen-more-info - Question is different to wire-frame design document
Question is different to wire-frame design document
Changed the label header in page.json file 
Tested manually

PAF-197 Question label is different from the wire-frame

---

apps/paf/behaviours/set-transport-toggle.js
apps/paf/fields/index.js
apps/paf/translations/src/en/fields.json
apps/paf/views/partials/crime-hgv-group.html
apps/paf/views/partials/report-person-transport-hgv-group.html
lib/ims-hof-values-map.json
test/_unit/behaviours/set-transport-toggle.spec.js

[PAF-195](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-195) 
Wrong Spelling - 'What is the vehicle type?' - 'HGV refridgerated' changed to HGV refrigerated'
- Replace the spelling error in 
> apps/paf/translations/src/en/fields.json 
> apps/paf/views/partials/report-person-transport-hgv-group.html
> lib/ims-hof-values-map.json
> apps/paf/behaviours/set-transport-toggle.js
> apps/paf/fields/index.js
> test/_unit/behaviours/set-transport-toggle.spec.js
Tested manually

PAF-195 Replaced spelling error on UI

---

hof.settings.json
test/_unit/server.spec.js

[PAF-131](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-131) Fix bug to display accessibility statement link when user click.
On click  Accessibility statement link navigates to page not found page
on hof.setting.json file , i have set getAccessibility to true 
- done a manual test for the task
- added line to unit testing to pass on drone

PAF-131: Fix bug where accessibility statement link navigates to page not found page

---

kube/app/deployment.yml
kube/file-vault/file-vault-deployment.yml
kube/file-vault/file-vault-ingress.yml

Edited references to FILE_VAULT_URL across deployments for PAF app and file-vault so that they all use the same URL
Also updated the file-vault ingress file so that the format matches other contemporary forms.
QAT team were unable to retrieve uploaded files in the UAT environment due to a mismatch of URLs causing incorrect redirection from filevault login, or incorrect logging of retrieval URLs causing a page not found error.
Updated conditional variable declaration in deployment and ingress files.
This will not be possible to test until it has reached UAT environment.

Fix discrepancies between fv URLs across deployments and ingress (UAT/STG/PROD)

---

apps/paf/fields/index.js
apps/paf/translations/src/en/fields.json
lib/ims-hof-values-map.json

What is your gender?' last option is shown as 'I don't know' but should be 'Prefer not to say'.  - [PAF-132](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-132)
Part of PAF requirement
- Changed gender-unknown options to prefer-not-to-say for report-person-gender, personAddGender and about-you-gender  fields  in fields/index.js
- Label changed from I don't know to Prefer not to say  for report-person-gender, personAddGender and about-you-gender  fields  in fields.json
- Changed values for HOF -key from gender-unknown to prefer-not-to-say in ims-hof-values-map.json
Testing passing  locally
Confirmed with DM. As long as prefer not to say is on the frontend, don't know is fine in IMS as we 'don't know' the gender. As long as we document it, so we know what we did when we move from …

PAF-132 Gender-unknown fix

---

kube/file-vault/file-vault-deployment.yml

Updated `file-vault-deployment.yml` to fix an issue causing the pod to fail to deploy in UAT
Following recent merged PR #122 The file-vault pod cannot start because the file-vault reverse proxy requires a https/TLS address to connect to. The prefixing of `https://` to the previous update was not done by mistake. This PR fixes that error.
Updated deployment to add https to conditional URL declaration

Filevault URL fix update: URLs must be https

---

apps/paf/views/partials/side-nav.html
assets/js/index.js
assets/scss/app.scss

Highlight sections on menu navigation - [PAF-166](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-166)
- When a user is on a question page within a given section the section should be highlighted in the menu
- Add element ids to side-nav html
- Set current url and class list for navigation sections in assets/js/index.js
- Add css styling for highlighting navigation sections in assets/css/app.scss
- tests passing locally

PAF 166:Highlight sections on menu navigation

---

apps/paf/behaviours/unset-crime-country.js
apps/paf/fields/index.js
apps/paf/index.js
apps/paf/translations/src/en/validation.json

[PAF-128](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-128) Country' fields allow any text 
[PAF-129](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-129)- All 'Country' fields allow any text without the use of drop down list
remove any url from the input text and accept validation entry.
this validation with control the textbox for both country and phone numbers
- added validation attribute in the field/index.js file 
- added validation message in the validation.js file
Manual testing via UI

PAF-129/ PAF-128 - Fix bug to add country from list and validate country textbox.

---

kube/ims-resolver/ims-resolver-deploy.yml

* Add image containing PAF-61 changes to IMS-resolver deployment
* Update the IMS-resolver env to pull in the correct configmap for UAT
* Add Keycloak variables to IMS resolver deployment env from secret
This PR allows PAF to deploy with [changes made to IMS-resolver for PAF-61](https://github.com/UKHomeOffice/ims-resolver/pull/17)
IMS-resolver requires Keycloak secrets to authenticate when retrieving uploaded documents to pass on to IMS via file-vault.
Previously the deployment was pulling the wrong configmap into UAT for ims-resolver. This should be fixed with this update too.
Can be tested in branch once the pull request triggers a deployment

PAF-61 Update ims-resolver deployment to use branch image

---

.drone.yml
bin/deploy.sh

Updated config to tear down PR envs
The drone/cron jobs that should tear down branch environment deployments when a) the accompanying PR is merged to master or b) weekly at the end of the week is currently not succeeding.
This appears to be because of older config not correctly calling the branches or cron jobs.
* Updated `deploy.sh` section to include all microservices deployed by PAF in the relevant delete command
* Updated drone pipeline steps to find PR branches and run commands to tear down
Copied new config/alterations from IMA and ASC projects where the jobs appear to work ok.
The drone cron job in the PAF project (drone/paf/settings/cron is currently misnamed as `tear_down_envs` and so it doesn't run any specific step from the `drone.yml`. After these changes we need to create a …

Fix weekly branch environment teardown and PR merge branch teardown

---

apps/paf/fields/index.js
apps/paf/index.js
apps/paf/translations/src/en/fields.json
lib/ims-hof-values-map.json

[PAF-210](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-210) 
- Does the person work for British government - Is missing from the UAT environment
What type of job or occupation does the person have? Select Government Employee Next page Does the person work for the British government? is missing
- In report-person-occupation-type  and in the condition the value is changed to job-government-employee'
test locally and works fine

Paf 210 work for british government

---

apps/paf/fields/index.js
apps/paf/translations/src/en/validation.json
apps/paf/views/date-time-crime-will-happen.html

[PAF-196](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-196) -Time (hh,mm)drop downs are missing from date-time-crime-will-happen page
no bug found for the hour and minutes selected but, Error message not display for date when past date selected
- add error message in validation.json file
- capture the current year then implement the logic on the date textbox in Fields/index.js file
test locally and works fine

PAF-196 validation for date, only accept future date

---

apps/paf/fields/index.js
apps/paf/sections/summary-data-sections.js
test/_unit/sections/summary-data-sections.spec.js

PAF-207 Missing questions and answers on 'Check Your Answers' Page
In 'Check Your Answers' Page  questions and answers are missing
Additional fields 
'report-person-location-travel-to-uk-how',
'report-person-location-travel-to-uk-where'   are added  in summary-data-sections.js in person-contact
Tests are amended with new fields.
Tested locally

PAF-207-missing-questions-answers

---

.drone.yml

Remove ls command when starting kd container for weekly branch env teardown job
The command as the entrypoint to the job is possibly stopping the container from being up long enough to run the following teardown script. Removing this will make the script the entrypoint command of the container
Updated `drone.yml` file to change the pipeline step.
To be done overnight on the cron job.

Weekly teardown fix: Remove ls command from start of kd container

---

.drone.yml

What?
I've added Trivy Scanner to Pipeline and removed deprecated Anchore Scanner for the PAF service, see ticket
[https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-613](url)
Why?
Trivy will let you scan images, file systems and repositories for any vulnerabilities and issues. It will detect CVEs of OS packages, applications susceptibilities, and exposures of IaC in Terraform files, Kubernetes and Docker.
Drawback of Anchore Scanner is it’s significantly slower, the process of using it is more cumbersome, the output is less friendly and most importantly, it scans fewer CVEs.
See [https://collaboration.homeoffice.gov.uk/jira/browse/HOFF-613](url) for more information.
How?
Removed Anchore cve exception file and added trivy cve exception file in hof-services-config repo from PAF …

HOFF-613: Replace Anchore with Trivy

---

apps/paf/fields/index.js
apps/paf/index.js

Updated the conditional value upon which a user is shown a page to give further details on the reported person's job if it was  'Other' from the main list
The conditional value on `'report-person-occupation-type'` was incorrect and so users would not be shown the `/report-person-occupation-other` page. Without this the corresponding field in IMS cases will always be empty.
Tested locally and observed the `/report-person-occupation-other` appears when a user selects 'Other' in the `'report-person-occupation-type'` field on the previous page.
Observed that detail entered in the `/report-person-occupation-other` appeared in the corresponding field in a new case on PRP1 IMS.

PAF-214 Allow users to enter further details when the reported person's job is 'Other'

---

lib/ims-hof-fields-map.json

Added IMS mapping for the three 'more info' text boxes that conditionally display on the crime-delivery page when certain radio options are selected.
It was observed that data entered into these boxes would not show up in a submitted case on IMS. This was because the mapping between these fields and IMS was not established
Added new field mappings for the three text boxes to `lib/ims-hof-fields-map.json`
Tested from local and observed correct data entered into the field in IMS cases for each of the three options that provides an opportunity to give more information.
Further testing to be done on branch, UAT
The three new fields from the HOF form map into the same IMS field. It was observed that if a user had entered info into all three fields the webform will only submit the info related …

PAF-216 Add IMS mapping for crime-delivery page text boxes

---

.drone.yml

Hardcode branch env name in `.drone.yml` to see if this affects the unsuccessful weekly teardown job.
Something is stopping the KD container from starting and running the command altered here. It can be run manually from the drone debugger when sas-paf-branch is added as an argument to the script.
Hardcoding that as it would be run manually to see if this improves things.

Teardown - try hardcode branch env name in drone.yml

---

apps/paf/behaviours/additional-person-formatter.js
apps/paf/behaviours/aggregator.js
apps/paf/fields/index.js
apps/paf/translations/src/en/fields.json
lib/ims-hof-person-add-values.json
lib/ims-hof-values-map.json

**What?**
Gender question - 'I don't know' for additional people shows up as 'add-gender-unknown'
**Why?**
There was no parse from value to label for additional people gender options
The mapping for gender options was incorrect
**How?**
Added a parse function for additional people gender options and created separate mapping for additional people
**Testing?**
Manual testing on local, branch and UAT forms and checking on Verint UI (PRP1)

Bug fix : Gender question - 'I don't know' for additional people shows up as 'add-gender-unknown'

---

lib/ims-hof-values-map.json

What?
The organisation company type dropdown value is not being set in IMS when Care home is selected in the dropdown
Why?
The mapping from hof to ims value for Care how was incorrect
How?
Corrected the mapping
Testing?
Manual testing on local, branch and UAT forms and checking on Verint UI (PRP1)

Corrected mapping for care home company type

---

kube/app/networkpolicy-external.yml

* ITHC and Automation testers of EBSA require access
* Allow Public access to UAT ingress url for a duration (temporarily)
* Please refer to the ticket [https://collaboration.homeoffice.gov.uk/jira/browse/PAF-241](url)
Currently the PAF UAT external url is restricted to POISE users only. ITHC and automated testers require access from EBSA, however EBSA is not willingly to share IP addresses to whitelist.
The hof team has decided to provide public access to https://paf.uat.sas-notprod.homeoffice.gov.uk/start for the duration of the ITHC and automated testing.
"cert-manager.io/enabled" will toggle cert-manager to handle to ingress resource. "cert-manager.io/solver: route53" label is added as the domain is whitelisted in namespaces hosted by AWS by Route53. 
please refer to ACP documentation …

PAF-241: Public access to PAF UAT External url temporarily

---

apps/paf/data/nationalities.json
lib/ims-hof-values-map.json

Removed 'Unknown' from the Nationality List
There are two similar options in the Nationality drop down - 'Unknown' and 'Nationality Currently Unknown', as there is no 'Unknown' in the current form, I have removed this
Tested form in local, branch and UAT

Removed redundant value and label Unknown from the Nationality list

---

apps/paf/fields/index.js
apps/paf/translations/src/en/fields.json

Removed the 'I don't know' option for the question 'Do you wish to report an individual'
There is no corresponding value in IMS 
Removed the 'I don't know' option from report-person
Test manually in local, branch and UAT

Removed the 'I don't know' option for the question 'Do you wish to report an individual'

---

apps/paf/fields/index.js
kube/ims-resolver/ims-resolver-deploy.yml

**What**
Removed resolve error when there is a failure while sending to ims so that allegation stays in the sqs and can be consumed again
**Why**
When the error is resolved the allegation is removed from SQS and is lost.
**How**
Removed resolve error from the code
**Test**
Tested locally by submitting an allegation with ops-nonlive turned off. An error was logged and the allegation was not sent. Connected to ops-nonlive and allegation was sent.
In branch and UAT this can be tested by submitting when PRP1 is turned off after hours and check next day if the allegation has been received in IMS

Updated ims-resolver to not resolve error when there is ims failure

---

bin/deploy.sh

**What?**
We are seeing deployment issues in sas-paf-prod. Those secrets issued by certs aren't the actual onces being used by the deployments. I have looked at the Services ASC and IMA. They aren't deploying these certs to prod from deploy.sh script.
These work is part of resolving PAF prod  deployment issues
https://collaboration.homeoffice.gov.uk/jira/browse/PAF-253
**Why?**
We need to remove these misconfigured secrets which arent used by deployments.
**How?**
These secrets are already deployed using kubectl commands in paf prod by Shamil. After reviewing other hof services where these(secrets & Certs) are not part of deploy scripts , We have decided to deploy the secrets and certificates using kubectl commands.
These are the example/references that lead us to make this change,
ASC : …

PAF-253: Remove Certs from deploy scripts for PAF prod 

---

.snyk

[PAF-257 - Pipeline failure on snyk_scan](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-257)
Two issues are identified by snyk scan:
"Open Redirect" [Medium Severity][https://security.snyk.io/vuln/SNYK-JS-EXPRESS-6474509] in express@4.18.2
introduced by hof@20.4.0 > express@4.18.2 and 1 other path(s)
"Information Exposure" [Medium Severity][https://security.snyk.io/vuln/SNYK-JS-FOLLOWREDIRECTS-6444610] in follow-redirects@1.15.3
introduced by hof@20.4.0 > notifications-node-client@6.0.0 > axios@0.25.0 > follow-redirects@1.15.3
Both have been whitelisted in PAF until they can be addressed in HOF.

Add exceptions to synk whitelist

---

apps/paf/fields/index.js

The [ticket PAF-249](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-249) surfaced a couple of phone number fields that should have been optional. Further investigation and testing revealed a total of thirteen fields that required to have the `required` flag removing from their validator. Two fields for telephone numbers was upgraded to validate phone numbers.
The user should be permitted to submit any page without being forced to fill any field.
Removal of the `required` flag from validation and application of the `internationalPhoneNumber` flag where appropriate.
Manual observation of pages.

PAF-249 required validator removed to make fields optional

---

package.json
yarn.lock

[PAF-260 Snyk pipeline failure](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-260)
Snyk scan reporting:
```
Issues with no direct upgrade or patch:
✗ Information Exposure Through Sent Data [Medium Severity]https://security.snyk.io/vuln/SNYK-JS-PHIN-6598077 in phin@2.9.3
introduced by jimp@0.22.10 > @jimp/plugins@0.22.10 > @jimp/plugin-print@0.22.10 > load-bmfont@1.4.1 > phin@2.9.3
This issue was fixed in versions: 3.7.1
```
Scanning with depcheck indicates `jimp` unused throughout project.
`jimp` removed

Snyk dependency issue: jimp

---

apps/paf/fields/index.js
apps/paf/translations/src/en/validation.json

email validation on the `paf/report-person-study-contact` page was reporting invalid on known valid email addresses.
There was an additional validation on the `report-person-study-email` field preventing validation.
The `report-person-study-email` field requires only the `email` validator.
Tested locally

PAF-261 email validation false negative

---

apps/paf/data/addPersonNationalities.json
apps/paf/data/nationalities.json

[ticket PAF-255](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-255)
There were a couple of mis-spellings of Philippines in the country lists.
It is important to have the correct spelling of Country names.
The mis-spelled words were identified and corrected.
Tested locally.
Screenshots of a mis-spelling and a correct spelling are available in the ticket.

PAF-255 Country spelling correction

---

apps/paf/fields/index.js

[ticket PAF-258](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-258)
/paf/person-details
Gender should be blank as user not selected any gender
Actual Result
`fields[personAddGender].options.[]`
The field parser was not handling the null case. It now returns the empty string.

PAF-258 person-details Gender 

---

kube/ims-resolver/ims-resolver-deploy.yml

* Remove secure connection and certs temporarily
* Currently we can curl but we can't send data to IMS via the app, strip out this complexity to see if it helps

PAF-264 fix prod integration, remove certs

---

apps/common/index.js
apps/common/translations/src/en/pages.json
apps/common/views/accessibility.html
apps/common/views/content/accessibility.md
hof.settings.json
test/_unit/server.spec.js

[PAF-251 - Update Accessibility Statement](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-251)
Add a PAF-specific Accessibility Statement.
The HOF default Accessibility Statement is to be replaced with a PAF-specific version.
The HOF default AS page was disabled. A new static page was added at `/accessibility` via the "common" routes. The page is described in markdown. One point of interest is the css override required for a numbered list which are disabled by default in GDS.
Manual testing

PAF-251 accessibility statement

---

.snyk
kube/ims-resolver/ims-resolver-deploy.yml

Update the ims-resolver image in its deployment.
The latest image contains the following updates:
- handleMessage function rejects its promise in the case of an error from its processing.
- Timestamps for error logs from handleMessage function
- Less generic logging
According to the [SQS-consumer module docs](https://www.npmjs.com/package/sqs-consumer): "Throwing an error (or returning a rejected promise) from the handler function will cause the message to be left on the queue". 
Doing this will hopefully cause failed message processing to not crash the container due to handleException errors from node. It will also help any messages with critical failures to head to the dead letter queue. 
This rejection is present in the icasework resolver but has not been added to ims-resolver until …

Update ims-resolver image to latest with reject failed msgs update

---

kube/ims-resolver/ims-resolver-deploy.yml

* IMS-resolver in production is being tested with 2 replicas.
* Team working on adding features in Branch
* PAF-248 requires replicas to be set to zero for branch
These changes are required for the IMS-Resolver which can be seen having Out of Memory issue resulting in restarts.
This Ensures there is always a stable set of running pods. It also Guarantee the availability of a specified number of identical Pods
Adding the If condition to apply these changes only to the deployment in Production.
We will be monitoring the pod and this should eventually resolved the issues with memory
We are waiting for ACP to add Visibility Time out for SQS queue.
https://support.acp.homeoffice.gov.uk/servicedesk/customer/portal/1/ACP-19768
We are also looking at adding Auto Scaling
here is an [example …

PAF-289: Update Replicas count to 2 for ims-resolver in prod and to 0 for ims-resolver in branch

---

apps/paf/models/file-upload.js
kube/file-vault/file-vault-deployment.yml
kube/ims-resolver/ims-resolver-deploy.yml
test/_unit/models/file-upload.spec.js

- Generate Filevault link to last forever instead of 7 days - [PAF-284](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-284)
- Revert ims-resolver pod replica to 1 - [PAF-292](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-292)
- Currently the expiry time for filevault links  for PAF is 7 days. This change will ensure the link lasts forever to prevent being unable to access attachments particularly when the IMS casework system goes down before forms have been successfully sent.
- A 'deadlock' error was triggered when the replicas were increased to 2 on prod so they have been reverted to 1 to avoid this error (previous changes to increase memory should continue to prevent 'out of memory' errors - ([PAF-289](https://github.com/jira/browse/PAF-289))).
- Amended the file …

PAF-248 and PAF-292: Generate Filevault link to last forever instead of 7 days and revert ims-resolver pod replicas

---

.snyk
apps/paf/behaviours/set-navigation-section.js
apps/paf/index.js
test/_unit/behaviours/set-navigation-section.spec.js

[PAF-286](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-286) - About you navigation button not working.
When about you button is clicked, it redirect to different page 
- Removed the next property from the "/add-other-info-file-upload and /other-info-file-upload" in the index.js file. this will redirect to url to the last completed form is about you is clicked
- Added a few line in the set-navigation-section.js to handle the back button functionalities to enable user navigate to previous step list.
- Added test line to confirm it redirect correctly.
Tested on local machine. 

PAF-286 Bugfix for About you Nav

---

.drone.yml
Dockerfile
apps/paf/behaviours/send-to-sqs.js
apps/paf/models/file-upload.js
kube/ims-resolver/ims-resolver-deploy.yml
lib/utils.js
package.json
test/_unit/models/file-upload.spec.js
yarn.lock

- Update PAF to use version of HOFF framework using axios - [PAF-173](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-173)
- Hof was previously using the request.js module which is now deprecated. The request module has been replaced with axios
- update hof in package.json to version using axios
- update.yarn.lock
- refactor models/file-upload to work with axios
- refactor file-upload tests
- update node version to version 20
- replace console.logs with hof logger
- remove unnecessary comments from ims-resolver-deployment.yml as the commented env is not in use

PAF-173: Update PAF to version of hof using axios

---

.snyk
test/_unit/models/file-upload.spec.js

Remove .only from describe block in file-upload unit test - [PAF-304](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-304)
Unit tests are currently only running one test
- remove .only from describe block in file-upload.spec.js
test passing locally and on branch
- updated snyk list

PAF-304: Remove '.only' from file-upload unit test to run all unit tests

---

.snyk
apps/common/index.js
apps/common/views/accessibility.html
apps/paf/index.js
hof.settings.json
package.json
yarn.lock

Update hof version in PAF to implement session timeout warning - [PAF-310](https://collaboration.homeoffice.gov.uk/jira/browse/PAF-310)
To comply with WCAG 2.2 accessibility requirements
- updated hof to version ~22.1.1 to implement session timeout message
- added hof session timeout behaviour to hof.settings.json
- added '/exit' steps to app' index.js
- added '/session-timeout' step to common/index.js
- amended accessibility.html to static page so it does not display session timeout message
- added views property to hof.settings. json to show custom accessibility page
- updated yarn.lock
tested locally
session timeout warning
'/exit' page
'/session-timeout' page
- updated snyk list
here is an [example commit](https://github.com/UKHomeOfficeForms/hof/commit/810959f391187c7c4af6db262bcd143b …

PAF-310: Update hof version to implement session timeout warning
